filebeat.inputs:
  - type: filestream
    id: syslog-stream
    paths:
      - /var/log/syslog
      - /var/log/auth.log
      - /var/log/fail2ban.log
    processors:
      - add_fields:
          target: event
          fields:
            dataset: "syslog"

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
  - add_docker_metadata: ~

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: ${CA_CERT}
